name: Deploy to GitHub Pages

on:
  #push:
  #  branches: [ main ]
  release:
    types: [ published ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

#concurrency:
#  group: "pages"
#  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    #defaults:
    #  run:
    #    working-directory: ./svc-web-redirect

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.2.0
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v6
        with:
          static_site_generator: sveltekit

      - name: Build
        env:
            BASE_PATH: /${{ github.event.repository.name }}
        run: bun run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
            path: 'build/'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v5
